---
title: "Untitled"
author: "刘嘉玲"
date: "2019.9.10"
output:
  html_document: default
  pdf_document: default
---
##1.创建一个有3个字段的数据框
```{r}
star1 <- c("邓超","赵丽颖","郭富城","周润发","杰克布莱克","汤唯")
birthyear <- c("1979","1987","1965","1955","1969","1979")
gender <- c("男","女","男","男","男","女")
id <- c(1,2,3,4,5.6)
stars <- data.frame(star1,birthyear,gender)
stars
```

##2.读入电影数据，并查看其前六行

```{r}
movies <- read.csv("C:\\Users\\hp\\Desktop\\电影数据.csv")
library(readxl)
movie <- c(read_excel("C:\\Users\\hp\\Desktop\\电影数据.xlsx"))
movie1 <- head(movies,n=6)
movie1
```

##3.查看读入的数据的数据结构类型

```{r}
class(movie)
```

##4.查看每个字段的数据类型
```{r}
str(movie)
```

##5.添加一列数据prefer

```{r}
prefer = 1:6
movie1$pre = prefer
head(movie1)
```


##6.查看第3行的电影信息
```{r}
movies[3,]
```

##7.查看第8列主演者的名字
```{r}
movies[,8]
```


##8.用$符号通过列名引用
```{r}
movie$star1
```

##9.选择数据中的动作电影
```{r}
action=movie[movie$type == "动作"]
action
```

##10.放映时间超过100分钟的动作电影
```{r}
action_long <- movie[movie$type == "动作" & movie$duration > 100]
action_long
```

##11.将movie前3行数据和stars按照列star1匹配并合并起来
```{r}
(movie.star = merge(movies[1:3,], stars,by = "star1")) 
```

END
